import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: "class",
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#5c0002",
        "outline-variant": "#5d3f3b",
        "on-tertiary-fixed": "#001f29",
        "inverse-surface": "#fcdbd6",
        "inverse-primary": "#c0000a",
        "tertiary-container": "#1d9cc3",
        "on-tertiary": "#003545",
        "tertiary-fixed-dim": "#68d3fc",
        "on-tertiary-fixed-variant": "#004d63",
        "outline": "#ad8883",
        "surface-bright": "#493431",
        "surface-container-lowest": "#190a08",
        "on-primary": "#690003",
        "surface-container": "#2d1b18",
        "surface-tint": "#ffb4aa",
        "on-error-container": "#ffdad6",
        "primary-container": "#ff5545",
        "on-secondary-container": "#00285c",
        "on-primary-fixed-variant": "#930005",
        "tertiary": "#68d3fc",
        "surface": "#1f0f0d",
        "background": "#1f0f0d",
        "surface-container-high": "#392522",
        "surface-dim": "#1f0f0d",
        "on-secondary-fixed-variant": "#004493",
        "secondary": "#adc6ff",
        "inverse-on-surface": "#402b29",
        "on-error": "#690005",
        "secondary-container": "#4b8eff",
        "error-container": "#93000a",
        "on-tertiary-container": "#002e3c",
        "on-surface-variant": "#e7bdb7",
        "primary": "#ffb4aa",
        "on-background": "#fcdbd6",
        "on-surface": "#fcdbd6",
        "surface-container-low": "#291715",
        "secondary-fixed-dim": "#adc6ff",
        "tertiary-fixed": "#bbe9ff",
        "on-secondary": "#002e69",
        "error": "#ffb4ab",
        "surface-variant": "#44302d",
        "primary-fixed": "#ffdad5",
        "on-secondary-fixed": "#001a41",
        "on-primary-fixed": "#410001",
        "secondary-fixed": "#d8e2ff",
        "surface-container-highest": "#44302d",
        "primary-fixed-dim": "#ffb4aa"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        xl: "64px",
        margin: "20px",
        sm: "12px",
        gutter: "16px",
        xs: "8px",
        lg: "40px",
        md: "24px",
        base: "4px"
      },
      fontFamily: {
        h1: ["Syne", "sans-serif"],
        h2: ["Syne", "sans-serif"],
        h3: ["Syne", "sans-serif"],
        "body-lg": ["Syne", "sans-serif"],
        "body-md": ["Syne", "sans-serif"],
        "tactical-data": ["Space Mono", "monospace"],
        badge: ["Space Mono", "monospace"],
        "tactical-label": ["Space Mono", "monospace"],
        sans: ['Syne', 'sans-serif'],
        mono: ['Space Mono', 'monospace'],
      },
      fontSize: {
        h1: ["40px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        h2: ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        h3: ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.5", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "tactical-data": ["14px", { lineHeight: "1.2", fontWeight: "400" }],
        "tactical-label": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        badge: ["10px", { lineHeight: "1", fontWeight: "700" }],
      }
    },
  },
  plugins: [],
};

export default config;

